version: '2'
services:
  
  node:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    links:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_NAME=heroku
      - DATABASE_USER=root
      - DATABASE_PASSW=root


  mysql:
    image: mysql
    ports:
      - "3306:3306" 
    environment:
        #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "../sql/config:/etc/mysql/conf.d"
      - "../sql/sqldump:/var/lib/mysql"
    
  
  